# alert.py
# Vet alert system.
# Primary: mailto: link (zero dependencies, always works for demo)
# Bonus: Twilio SMS (comment in if you have an account)

import urllib.parse
from typing import Optional


# ── mailto: alert (primary — use this for demo) ───────────────────────────────

def build_mailto_link(
    vet_email: str,
    animal_type: str,
    severity: str,
    vet_summary: str,
    conditions: list[dict],
) -> str:
    """
    Builds a mailto: link with a pre-filled subject and body.
    Farmer clicks → their email client opens with everything filled in.
    """
    subject = f"[FarmGuard Alert] {severity} - {animal_type} needs attention"
    
    conditions_text = "\n".join(
        f"  - {c['name']} (confidence: {c['confidence']}): {c.get('explanation', '')}"
        for c in conditions
    )
    
    body = f"""FARMGUARD AI LIVESTOCK ALERT
{'='*40}

Severity: {severity}
Animal: {animal_type}

POSSIBLE CONDITIONS:
{conditions_text}

SUMMARY:
{vet_summary}

---
This alert was generated by FarmGuard AI based on farmer-reported symptoms.
Please follow up with the farmer directly to confirm and advise.
"""
    
    params = urllib.parse.urlencode({"subject": subject, "body": body})
    return f"mailto:{vet_email}?{params}"


def build_alert_message(
    animal_type: str,
    severity: str,
    conditions: list[dict],
    vet_summary: str,
) -> str:
    """Returns the plain-text message used in any alert method."""
    conditions_text = ", ".join(
        f"{c['name']} ({c['confidence']} confidence)"
        for c in conditions
    )
    return (
        f"FarmGuard Alert [{severity}] | {animal_type}\n"
        f"Possible: {conditions_text}\n"
        f"{vet_summary[:300]}..."
    )


# ── Twilio SMS (bonus — comment in if you have an account) ───────────────────

def send_sms_alert(
    to_phone: str,
    from_phone: str,
    account_sid: str,
    auth_token: str,
    animal_type: str,
    severity: str,
    conditions: list[dict],
    vet_summary: str,
) -> bool:
    """
    Send SMS alert via Twilio.
    Only use this if you have a Twilio account set up.
    For judge mode, disable this and use mailto: instead.
    
    Returns True on success, False on failure.
    """
    try:
        from twilio.rest import Client
        
        client = Client(account_sid, auth_token)
        message_body = build_alert_message(animal_type, severity, conditions, vet_summary)
        
        # Twilio SMS has 1600 char limit
        if len(message_body) > 1600:
            message_body = message_body[:1597] + "..."
        
        client.messages.create(
            body=message_body,
            from_=from_phone,
            to=to_phone,
        )
        return True
    
    except ImportError:
        print("Twilio not installed. Run: pip install twilio")
        return False
    except Exception as e:
        print(f"Twilio error: {e}")
        return False


# ── Judge mode: simulated alert (no real send) ────────────────────────────────

def simulate_alert(animal_type: str, severity: str, vet_summary: str) -> dict:
    """
    For judge mode — simulates sending an alert without any real API call.
    Returns a mock confirmation dict.
    """
    return {
        "status": "simulated",
        "message": f"[JUDGE MODE] Alert would be sent for {animal_type} ({severity})",
        "preview": vet_summary[:200] + "...",
    }
