# alert.py
# Vet alert system.
# Primary: mailto: link (zero dependencies, always works for demo)
# Bonus: Twilio SMS (comment in if you have an account)

import urllib.parse
from typing import Optional


# ── mailto: alert (primary — use this for demo) ───────────────────────────────

def build_mailto_link(
    vet_email: str,
    animal_type: str,
    severity: str,
    vet_summary: str,
    conditions: list[dict],
    answers: dict = None,
    chicken_type: str = None,
) -> str:
    import datetime
    report_date = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")

    subject = f"[FarmGuard Alert] {severity} — {animal_type} needs attention"

    animal_line = animal_type
    if chicken_type:
        animal_line += f" ({'Single Bird' if chicken_type == 'single' else 'Flock'})"

    conditions_text = "\n".join(
        f"  • {c['name']} ({c.get('confidence','?')} confidence)\n"
        f"    {c.get('explanation', '')}"
        for c in conditions
    )

    if answers:
        skip_keys = {"chicken_count"}
        lines = []
        for key, val in answers.items():
            if key in skip_keys:
                continue
            label = key.replace("_", " ").replace("flock ", "").replace("single ", "").title()
            display = ", ".join(val) if isinstance(val, list) else val
            if display and display not in ("None", "None of these", "['None']"):
                lines.append(f"  • {label}: {display}")
        symptoms_text = "\n".join(lines) if lines else "  • No specific symptoms recorded"
    else:
        symptoms_text = "  • (Symptom detail not available)"

    body = f"""FARMGUARD AI — FARM INCIDENT REPORT
{'=' * 44}
Generated: {report_date}
Severity:  {severity}
Animal:    {animal_line}

SYMPTOMS REPORTED BY FARMER
{'-' * 44}
{symptoms_text}

POSSIBLE CONDITIONS (AI Assessment)
{'-' * 44}
{conditions_text}

VET SUMMARY
{'-' * 44}
{vet_summary}

{'=' * 44}
This report was auto-generated by FarmGuard AI based on farmer-reported symptoms.
It is not a substitute for professional veterinary diagnosis.
Please follow up with the farmer directly to confirm and advise.
"""

    params = urllib.parse.urlencode({"subject": subject, "body": body}, quote_via=urllib.parse.quote)
    return f"mailto:{vet_email}?{params}"


def build_alert_message(
    animal_type: str,
    severity: str,
    conditions: list[dict],
    vet_summary: str,
) -> str:
    """Returns the plain-text message used in any alert method."""
    conditions_text = ", ".join(
        f"{c['name']} ({c['confidence']} confidence)"
        for c in conditions
    )
    return (
        f"FarmGuard Alert [{severity}] | {animal_type}\n"
        f"Possible: {conditions_text}\n"
        f"{vet_summary[:300]}..."
    )


# ── Twilio SMS (bonus — comment in if you have an account) ───────────────────

def send_sms_alert(
    to_phone: str,
    from_phone: str,
    account_sid: str,
    auth_token: str,
    animal_type: str,
    severity: str,
    conditions: list[dict],
    vet_summary: str,
) -> bool:
    """
    Send SMS alert via Twilio.
    Only use this if you have a Twilio account set up.
    For judge mode, disable this and use mailto: instead.
    
    Returns True on success, False on failure.
    """
    try:
        from twilio.rest import Client
        
        client = Client(account_sid, auth_token)
        message_body = build_alert_message(animal_type, severity, conditions, vet_summary)
        
        # Twilio SMS has 1600 char limit
        if len(message_body) > 1600:
            message_body = message_body[:1597] + "..."
        
        client.messages.create(
            body=message_body,
            from_=from_phone,
            to=to_phone,
        )
        return True
    
    except ImportError:
        print("Twilio not installed. Run: pip install twilio")
        return False
    except Exception as e:
        print(f"Twilio error: {e}")
        return False


# ── Judge mode: simulated alert (no real send) ────────────────────────────────

def simulate_alert(animal_type: str, severity: str, vet_summary: str) -> dict:
    """
    For judge mode — simulates sending an alert without any real API call.
    Returns a mock confirmation dict.
    """
    return {
        "status": "simulated",
        "message": f"[JUDGE MODE] Alert would be sent for {animal_type} ({severity})",
        "preview": vet_summary[:200] + "...",
    }